In [2]:
import numpy as np

In [6]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [7]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [8]:
data[names == 'Bob'] #布尔型数组用于数组索引

array([[-0.97826225, -0.53029096,  0.23066342, -1.88909257],
       [ 0.8138775 ,  1.12528385, -2.47364663, -0.14364744]])

In [9]:
# 注意：如果布尔型数组的长度不对，布尔型选择就会出错，因此一定要小心。

In [10]:
data[names == 'Bob', 2:]

array([[ 0.23066342, -1.88909257],
       [-2.47364663, -0.14364744]])

In [11]:
data[names == 'Bob', 3]

array([-1.88909257, -0.14364744])

In [12]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [13]:
data[~(names == 'Bob')] # ~也可用于否定，与！相似

array([[ 0.50528121,  0.22416856, -0.02958596, -0.33386914],
       [-2.02088631, -2.62232523,  0.07411028, -0.72116315],
       [ 0.20518161, -0.01203953, -0.78807713,  0.06574516],
       [-1.09465894, -0.64326243,  0.65121304,  0.09412321],
       [ 0.54395346,  0.58127327, -0.49915736, -0.42927518]])

In [14]:
cond = names == 'Bob' # 先做布尔数组
data[~cond] # 反向条件

array([[ 0.50528121,  0.22416856, -0.02958596, -0.33386914],
       [-2.02088631, -2.62232523,  0.07411028, -0.72116315],
       [ 0.20518161, -0.01203953, -0.78807713,  0.06574516],
       [-1.09465894, -0.64326243,  0.65121304,  0.09412321],
       [ 0.54395346,  0.58127327, -0.49915736, -0.42927518]])

In [15]:
mask = (names == 'Bob') | (names == 'Will') #布尔数组可以使用or and逻辑符号
mask

array([ True, False,  True,  True,  True, False, False])

In [16]:
data[mask]

array([[-0.97826225, -0.53029096,  0.23066342, -1.88909257],
       [-2.02088631, -2.62232523,  0.07411028, -0.72116315],
       [ 0.8138775 ,  1.12528385, -2.47364663, -0.14364744],
       [ 0.20518161, -0.01203953, -0.78807713,  0.06574516]])

In [17]:
data[data < 0] = 0 #做条件的bool数组
data

array([[0.        , 0.        , 0.23066342, 0.        ],
       [0.50528121, 0.22416856, 0.        , 0.        ],
       [0.        , 0.        , 0.07411028, 0.        ],
       [0.8138775 , 1.12528385, 0.        , 0.        ],
       [0.20518161, 0.        , 0.        , 0.06574516],
       [0.        , 0.        , 0.65121304, 0.09412321],
       [0.54395346, 0.58127327, 0.        , 0.        ]])

In [18]:
data[names != 'Joe'] = 7 #通过一维布偶数列设置整行或整列的值
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.50528121, 0.22416856, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.65121304, 0.09412321],
       [0.54395346, 0.58127327, 0.        , 0.        ]])

Fancy indexing（花式索引）

In [20]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
arr[[4, 3, 0, 6]] #以特定顺序选取行子集