In [2]:
import numpy as np

In [6]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [7]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [8]:
data[names == 'Bob'] #布尔型数组用于数组索引

array([[-0.97826225, -0.53029096,  0.23066342, -1.88909257],
       [ 0.8138775 ,  1.12528385, -2.47364663, -0.14364744]])

In [9]:
# 注意：如果布尔型数组的长度不对，布尔型选择就会出错，因此一定要小心。

In [10]:
data[names == 'Bob', 2:]

array([[ 0.23066342, -1.88909257],
       [-2.47364663, -0.14364744]])

In [11]:
data[names == 'Bob', 3]

array([-1.88909257, -0.14364744])

In [12]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [13]:
data[~(names == 'Bob')] # ~也可用于否定，与！相似

array([[ 0.50528121,  0.22416856, -0.02958596, -0.33386914],
       [-2.02088631, -2.62232523,  0.07411028, -0.72116315],
       [ 0.20518161, -0.01203953, -0.78807713,  0.06574516],
       [-1.09465894, -0.64326243,  0.65121304,  0.09412321],
       [ 0.54395346,  0.58127327, -0.49915736, -0.42927518]])

In [14]:
cond = names == 'Bob' # 先做布尔数组
data[~cond] # 反向条件

array([[ 0.50528121,  0.22416856, -0.02958596, -0.33386914],
       [-2.02088631, -2.62232523,  0.07411028, -0.72116315],
       [ 0.20518161, -0.01203953, -0.78807713,  0.06574516],
       [-1.09465894, -0.64326243,  0.65121304,  0.09412321],
       [ 0.54395346,  0.58127327, -0.49915736, -0.42927518]])

In [15]:
mask = (names == 'Bob') | (names == 'Will') #布尔数组可以使用or and逻辑符号
mask

array([ True, False,  True,  True,  True, False, False])

In [16]:
data[mask]

array([[-0.97826225, -0.53029096,  0.23066342, -1.88909257],
       [-2.02088631, -2.62232523,  0.07411028, -0.72116315],
       [ 0.8138775 ,  1.12528385, -2.47364663, -0.14364744],
       [ 0.20518161, -0.01203953, -0.78807713,  0.06574516]])

In [17]:
data[data < 0] = 0 #做条件的bool数组
data

array([[0.        , 0.        , 0.23066342, 0.        ],
       [0.50528121, 0.22416856, 0.        , 0.        ],
       [0.        , 0.        , 0.07411028, 0.        ],
       [0.8138775 , 1.12528385, 0.        , 0.        ],
       [0.20518161, 0.        , 0.        , 0.06574516],
       [0.        , 0.        , 0.65121304, 0.09412321],
       [0.54395346, 0.58127327, 0.        , 0.        ]])

In [18]:
data[names != 'Joe'] = 7 #通过一维布偶数列设置整行或整列的值
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.50528121, 0.22416856, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.65121304, 0.09412321],
       [0.54395346, 0.58127327, 0.        , 0.        ]])

Fancy indexing（花式索引）

In [20]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [21]:
arr[[4, 3, 0, 6]] #以特定顺序选取行子集

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [22]:
arr[[-3, -5, -7]] #负数取逆向

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [23]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [24]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] #一次传入多个数组，返回对应各个索引数组的一维数组

array([ 4, 23, 29, 10])

In [25]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] #按照此格式得到所需取值得矩阵

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [26]:
# 花式索引跟切片不一样，它总是将数据复制到新数组中

数组转置和轴对换

In [27]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
arr.T #转置

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])