In [1]:
import numpy as np

1. 创建ndarray

In [3]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1) # 1维数组
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)# 转换为多维数组
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr2.ndim #返回维数

2

In [7]:
arr2.shape # 返回形状

(2, 4)

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int32')

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr3 = np.array(range(3))
arr3

array([0, 1, 2])

In [26]:
np.full(3,3) #填满

array([3, 3, 3])

In [27]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [30]:
float_arr = arr.astype(np.float64) #转换数据类型
float_arr.dtype 

dtype('float64')

In [32]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32) #转换int类型，小数点后会被剔除

array([ 3, -1, -2,  0, 12, 10])

In [38]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.dtype

dtype('S4')

In [40]:
numeric_strings.astype(float).dtype 
#将纯数字的string转为float，numpy可将python类型转换为dtype

dtype('float64')

In [44]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype) #将其他narray的类型转换到本array中


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [55]:
empty_nint32 = np.empty(8, dtype = 'u4') # 使用代号定义dtype
empty_nint32 

array([3880093576,        598, 3828020096,        598,          0,
                0, 2147483648,    3014740], dtype=uint32)

In [62]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

2. 计算

In [57]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [58]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [60]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [61]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 >arr

array([[False,  True, False],
       [ True, False,  True]])

3. indexing and slicing(索引与切片)

In [63]:
arr = np.arange(10) #一维list
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr[5]

5

In [65]:
arr[5:8] #查找连续几个数值

array([5, 6, 7])

In [67]:
arr[5:8] = 12 #赋值
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [68]:
arr_slice = arr[5:8] #创建切片
arr_slice

array([12, 12, 12])

In [69]:
arr_slice[1] = 12345 #切片上的数据没有被复制，修改直接反映在原数组上（boardcasting）
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [70]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [72]:
arr2d = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]]) # 二维数组
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
arr2d[2]

array([7, 8, 9])

In [75]:
arr2d[0][2]
arr2d[0, 2] #两种方法等价

3

In [76]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 3维数组
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
arr3d[1, 0]

array([7, 8, 9])

In [81]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [82]:
x[0]

array([7, 8, 9])

In [83]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [84]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [85]:
arr2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [88]:
arr2d[1, :2]

array([4, 5])

In [89]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])